name: Shimgen CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-shimgen:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: compile
      run: cl /O1 scoop-better-shimexe/shim.c

    - uses: actions/upload-artifact@v4
      with:
        name: shim.exe
        path: shim.exe

